fix(liquidate): convert amountOut to assets when comparing to assets (c4 issue 427)
GenerationSoftware/pt-v5-vault pull request #6
Opened 2023-08-02 21:20 UTC by PierrickGT

2023-08-07 15:49 UTC, asselstine requested changes

2023-08-07 15:49 UTC, asselstine commented on src/Vault.sol
> +    uint256 _amountOutToAssets = _convertToAssets(_amountOut, Math.Rounding.Down);
suggest renaming this to `_assetAmountOut` for clarity

2023-08-07 18:51 UTC, PierrickGT commented on src/Vault.sol
> +    uint256 _amountOutToAssets = _convertToAssets(_amountOut, Math.Rounding.Down);
Done: https://github.com/GenerationSoftware/pt-v5-vault/pull/6/commits/2669cc6a9c4669067557c3fbd0fe79cb4dc3353b

2023-08-15 02:57 UTC, asselstine approved these changes

2023-08-15 02:57 UTC, merged